[versions]
ireader = "1.2-SNAPSHOT"
ktor = "2.0.0"



[libraries]

android-sdklib = "com.android.tools:sdklib:30.0.4"
android-gradle = "com.android.tools.build:gradle:7.1.2"

kotlinpoet = "com.squareup:kotlinpoet-ksp:1.10.2"

ireader-core = { module = "io.github.kazemcodes:core-api", version.ref = "ireader" }


okhttp = "com.squareup.okhttp3:okhttp:4.10.0-RC1"
jsoup = "org.jsoup:jsoup:1.14.3"
skrapeit = "it.skrape:skrapeit:1.2.1"
skrapeit-snaphsot = "it.skrape:skrapeit:0-SNAPSHOT"

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-core-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-gson = { module = "io.ktor:ktor-serialization-gson", version.ref = "ktor" }
