name: CI

on:
  push:
    branches:
      - master

jobs:
  check_wrapper:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  build:
    name: Build extension repo
    needs: check_wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master
          path: master

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Copy CI gradle.properties
        run: |
          cd master
          mkdir -p ~/.gradle
          cp .github/runner-files/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Build extensions and create repo artifacts
        uses: eskatos/gradle-command-action@v1
        env:
          CI_MULTISRC: "true"
          CI_CHUNK_NUM: ${{ matrix.chunk }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        with:
          build-root-directory: master
          wrapper-directory: master
          arguments: assembleRelease repo
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

      - name: Sign APKs
        if: github.event_name == 'push' && github.repository == 'IReaderorg/ireader-extension-test'
        run: |
          cd master
          ./.github/scripts/sign-apks.sh \
            ${{ secrets.SIGNING_KEY }} \
            ${{ secrets.ALIAS }} \
            ${{ secrets.KEY_STORE_PASSWORD }} \
            ${{ secrets.KEY_PASSWORD }}

      - name: Checkout repo branch
        if: github.event_name == 'push' && github.repository == 'IReaderorg/ireader-extension-test'
        uses: actions/checkout@v2
        with:
          ref: repo
          path: repo

      - name: Deploy repo
        if: github.event_name == 'push' && github.repository == 'IReaderorg/ireader-extension-test'
        run: |
          cd repo
          ../master/.github/scripts/commit-repo.sh
